name: Announce

on:
  release:
    types: [published]

jobs:
  announce:
    runs-on: ubuntu-latest
  
    steps:
    - name: Send announcement tweet!
      if: ${{ !github.event.release.prerelease }}
      uses: snow-actions/tweet@v1.4.0
      with:
        status: |
          Announcing the release of ExRam.Gremlinq ${{ github.event.release.tag_name }}!
          
          ExRam.Gremlinq is the first #dotnet object-graph-mapper for @apachetinkerpop #gremlin enabled #graphdb‎s like @AzureCosmosDB, @dotnetonAWS Neptune or @JanusGraph.
          
          ${{ github.event.release.html_url }}
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
