name: Build pull request

on:
  pull_request:
  workflow_call:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Build
      run: dotnet build ./${{ github.event.repository.name }}.sln -c Release -p:IsPackable=false

