name: Build + Test

on:
  push:
    branches:
      - main
      - \d+\.x
  pull_request:

env:
  IsForkedRepository: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
  DotNetVersion: '7.0.102'
  ProductName: 'ExRam.Gremlinq'

jobs:
  determinePublicationType:
    runs-on: ubuntu-latest
    
    outputs:
      publishToNuget: ${{ github.event_name == 'push' && steps.version-regex.outputs.match != '' }}
      publishToGithubPackages: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      
    steps:
      - name: Determine type of publication
        uses: actions-ecosystem/action-regex-match@v2.0.2
        id: version-regex
        with:
          text: ${{ github.ref }}
          regex: '^refs/heads/\d+\.x$'

  build:
    runs-on: ubuntu-latest

    outputs:
      semVer2: ${{ steps.nbgv.outputs.SemVer2 }}
      isPreviewRelease: ${{ startsWith(steps.nbgv.outputs.PrereleaseVersionNoLeadingHyphen, 'preview') }}
      isStableRelease: ${{ steps.nbgv.outputs.PrereleaseVersionNoLeadingHyphen == '' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'
        
    - name: Setup .NET ${{ env.DotNetVersion }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          ${{ env.DotNetVersion }}

    - name: Determine semantic version
      uses: dotnet/nbgv@master
      id: nbgv

    - name: Build
      run: dotnet build -c Release -p:ContinuousIntegrationBuild=true

    - name: Pack
      run: dotnet pack -c Release --no-build

    - name: Copy NuGet packages to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: NuGetPackages
        path: ./**/${{ env.ProductName }}.*.nupkg
        if-no-files-found: error

  test-linux:
    runs-on: ubuntu-latest

    services:
      gremlinServer:
        image: tinkerpop/gremlin-server
        ports:
          - 8182:8182
      janusgraph:
        image: janusgraph/janusgraph
        ports:
          - 8183:8182

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'
        
    - name: Setup .NET ${{ env.DotNetVersion }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          ${{ env.DotNetVersion }}

    - name: Test
      run: dotnet test  --configuration Release --verbosity normal
      env:
        RunGremlinServerIntegrationTests: ${{ env.IsForkedRepository == 'false' }}
        RunJanusGraphIntegrationTests: ${{ env.IsForkedRepository == 'false' }}

    - name: Copy *.received-files to artifacts
      if: ${{ always() && env.IsForkedRepository == 'false' }}
      uses: actions/upload-artifact@v2
      with:
        name: test-linux-received-snapshots
        path: ./**/*.received.*

  test-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Setup .NET ${{ env.DotNetVersion }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          ${{ env.DotNetVersion }}

    - name: Start CosmosDb Emulator
      uses: Gremlinq/cosmos-emulator-github-action@EnableGremlin

    - name: Test
      run: dotnet test  --configuration Release --verbosity normal
      env:
        RunCosmosDbIntegrationTests: ${{ env.IsForkedRepository == 'false' }}

    - name: Copy *.received-files to artifacts
      if: ${{ always() && env.IsForkedRepository == 'false' }}
      uses: actions/upload-artifact@v2
      with:
        name: test-windows-received-snapshots
        path: ./**/*.received.*

  create-snapshot-fix-pr:
    if: ${{ always() && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [ test-linux, test-windows ]
    env:
      pr-message: 'Fix snapshots for #${{ github.event.number }}.'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      continue-on-error: true
      with:
        name: test-linux-received-snapshots
        
    - uses: actions/download-artifact@v2
      continue-on-error: true
      with:
        name: test-windows-received-snapshots

    - name: Rename received files
      run: find . -type f -name '*.received.*' | while read FILE ; do newfile="$(echo ${FILE} |sed -e 's/received/verified/')"; mv "${FILE}" "${newfile}"; done 

    - name: Create snapshot changes pull request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: ${{ env.pr-message }}
        title: ${{ env.pr-message }}
        body: ${{ env.pr-message }}
        base: ${{ github.head_ref }}
        branch-suffix: short-commit-hash

  publish:
    needs: [ determinePublicationType, build, test-linux, test-windows ]
    runs-on: ubuntu-latest
    if: ${{ needs.determinePublicationType.outputs.publishToNuget == 'true' || needs.determinePublicationType.outputs.publishToGithubPackages == 'true' }}

    steps:

    - uses: actions/download-artifact@v2
      with:
        name: NuGetPackages

    - name: Push NuGet packages to GitHub packages
      if: ${{ needs.determinePublicationType.outputs.publishToGithubPackages == 'true' }}
      run: dotnet nuget push **/${{ env.ProductName }}.*.nupkg
        --source https://nuget.pkg.github.com/exram/index.json
        --api-key ${{ secrets.GITHUB_TOKEN }}
        --no-symbols
        --skip-duplicate

    - name: Push NuGet packages to NuGet.org
      if: ${{ needs.determinePublicationType.outputs.publishToNuget == 'true' }}
      run: dotnet nuget push **/${{ env.ProductName }}.*.nupkg
        --source https://api.nuget.org/v3/index.json
        --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
        --no-symbols
        --skip-duplicate

  cleanup:
    needs: [ publish ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [ExRam.Gremlinq.Core, ExRam.Gremlinq.Core.AspNet, ExRam.Gremlinq.Providers.WebSocket, ExRam.Gremlinq.Providers.WebSocket.AspNet, ExRam.Gremlinq.Providers.Core, ExRam.Gremlinq.Providers.Neptune.AspNet, ExRam.Gremlinq.Providers.Neptune, ExRam.Gremlinq.Providers.Core.AspNet, ExRam.Gremlinq.Providers.CosmosDb, ExRam.Gremlinq.Providers.CosmosDb.AspNet, ExRam.Gremlinq.Providers.GremlinServer.AspNet, ExRam.Gremlinq.Providers.GremlinServer, ExRam.Gremlinq.Providers.JanusGraph.AspNet, ExRam.Gremlinq.Providers.JanusGraph]
    
    steps:
    - uses: actions/delete-package-versions@v2
      continue-on-error: true
      with:
        package-name: ${{ matrix.name }}
        min-versions-to-keep: 10

  release:
    needs: [ determinePublicationType, build, publish ]
    runs-on: ubuntu-latest
    if: ${{ needs.determinePublicationType.outputs.publishToNuget == 'true' }}

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: NuGetPackages

    - name: Draft release
      id: create_release
      uses: release-drafter/release-drafter@v5.17.6
      with:
        name: ${{ env.ProductName }} ${{ needs.build.outputs.semVer2 }}
        prerelease: ${{ needs.build.outputs.isPreviewRelease }}
        tag: ${{ needs.build.outputs.semVer2 }}
        commitish: ${{ github.ref }}
        publish: true
      env:
        GITHUB_TOKEN: ${{ secrets.CREATE_RELEASE_PAT }}

    - uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: '**/${{ env.ProductName }}.*.nupkg'
        github_token: ${{ secrets.CREATE_RELEASE_PAT }}

