name: Build + Test

on:
  push:
    branches:
      - main
      - rel
  pull_request:

env:
  IsForkedRepository: ${{ (github.event_name == 'pull_request') && (github.event.pull_request.head.repo.full_name != github.repository) }}
  DotNetVersion: '5.0.102'

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      semVer2: ${{ steps.nbgv.outputs.SemVer2 }}
      isPrerelease: ${{ steps.nbgv.outputs.PrereleaseVersionNoLeadingHyphen != '' }}

    steps:
    - run: echo ${{ github.event_name }}
    - run: echo ${{ github.event.pull_request.head.repo.full_name }}
    - run: echo ${{ github.repository }}
    - run: echo ${{ env.IsForkedRepository }}
    - run: echo ${{ (github.event_name == 'pull_request') }}
    - run: echo ${{ (github.event.pull_request.head.repo.full_name != github.repository) }}
    - run: echo ${{ (github.event_name == 'pull_request') && (github.event.pull_request.head.repo.full_name != github.repository) }}
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Setup .NET Core ${{ env.DotNetVersion }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DotNetVersion }}

    - name: Install dotnet-validate
      run: dotnet tool install -g dotnet-validate --version 0.0.1-preview.51

    - name: Determine semantic version
      uses: dotnet/nbgv@master
      id: nbgv

    - name: Build
      run: dotnet build --configuration Release -p:ContinuousIntegrationBuild=true

    - name: Validate nuget packages
      run: dotnet validate package local **/ExRam.*.nupkg

    - name: Copy NuGet packages to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: NuGetPackages
        path: ./**/ExRam.*.nupkg
        if-no-files-found: error

  test-linux:
    runs-on: ubuntu-latest

    services:
      gremlinServer:
        image: tinkerpop/gremlin-server
        ports:
          - 8182:8182

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Setup .NET Core ${{ env.DotNetVersion }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DotNetVersion }}

    - name: Test
      run: dotnet test  --configuration Release --verbosity normal -p:RunGremlinServerIntegrationTests=${{ !env.IsForkedRepository }}

  test-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'
        
    - name: Start CosmosDb Emulator
      uses: southpolesteve/cosmos-emulator-github-action@v1
      env:
        AZURE_COSMOS_EMULATOR_GREMLIN_ENDPOINT: true

    - name: Setup .NET Core ${{ env.DotNetVersion }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DotNetVersion }}

    - name: Test
      run: dotnet test  --configuration Release --verbosity normal -p:RunCosmosDbEmulatorIntegrationTests=${{ !env.IsForkedRepository }}

  publish:
    needs: [ build, test-linux, test-windows ]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
    - name: Setup .NET Core ${{ env.DotNetVersion }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DotNetVersion }}

    - uses: actions/download-artifact@v2
      with:
        name: NuGetPackages

    - name: Push NuGet packages to GitHub packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: dotnet nuget push **/ExRam.*.nupkg
        --source https://nuget.pkg.github.com/exram/index.json
        --api-key ${{ secrets.GITHUB_TOKEN }}
        --no-symbols true
        --skip-duplicate

    - name: Push NuGet packages to NuGet.org
      if: ${{ github.ref == 'refs/heads/rel' }}
      run: dotnet nuget push **/ExRam.*.nupkg
        --source https://api.nuget.org/v3/index.json
        --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
        --no-symbols true
        --skip-duplicate

  announce:
    needs: [ build, publish ]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/rel' }}

    steps:
    - name: Draft release
      uses: release-drafter/release-drafter@v5.14.0
      with:
        name: ExRam.Gremlinq ${{ needs.build.outputs.semVer2 }}
        prerelease: ${{ needs.build.outputs.isPrerelease }}
        tag: ${{ needs.build.outputs.semVer2 }}
        commitish: ${{ github.ref }}
        publish: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Send announcement tweet!
      if: ${{ !needs.build.outputs.isPrerelease }}
      uses: ethomson/send-tweet-action@v1
      with:
        status: |
          Announcing the release of ExRam.Gremlinq ${{ needs.build.outputs.semVer2 }}!
          
          ExRam.Gremlinq is the first #dotnet object-graph-mapper for @apachetinkerpop #gremlin enabled #graphdb‎s like @AzureCosmosDB, #AWS #Neptune or @JanusGraph.
          
          https://github.com/ExRam/ExRam.Gremlinq/releases/tag/${{ needs.build.outputs.semVer2 }}
        consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
