name: Check pull request

on:
  pull_request:
  workflow_call:

jobs:

  test-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Build
      run: dotnet build ./${{ github.event.repository.name }}.sln -c Release
      
    - name: Test
      run: dotnet test ./${{ github.event.repository.name }}.sln -c Release --no-build
      env:
        RunGremlinServerIntegrationTests: 'true'
        RunJanusGraphIntegrationTests: 'true'
        RunNeptuneIntegrationTests: 'true'

    - name: Collect coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  test-windows:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Start CosmosDb Emulator
      uses: Gremlinq/cosmos-emulator-github-action@EnableGremlin

    - name: Build
      run: dotnet build ./${{ github.event.repository.name }}.sln -c Release
      
    - name: Test
      run: dotnet test ./${{ github.event.repository.name }}.sln -c Release --no-build
      env:
        RunCosmosDbIntegrationTests: 'true'
        
    - name: Collect coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}