name: Cleanup

on:
  registry_package:
    types: [published, updated]
  workflow_call:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/delete-package-versions@v4
      with:
        package-name: ${{ github.event.registry_package.name }}
        package-type: nuget
        min-versions-to-keep: 10

