name: 'Label Actions'

on:
  issues:
    types: [labeled]
  discussions:
    types: [labeled]

permissions:
  contents: read
  issues: write
  pull-requests: read
  discussions: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v2
        with:
          github-token: ${{ github.token }}